### signup
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "puja@gmail.com",
    "username": "puja",
    "password": "puja"
}

### login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "puja@gmail.com",
    "password": "puja"
}

### get tasks of user
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjczLCJlbWFpbCI6InB1amFAZ21haWwuY29tIiwiaWF0IjoxNzEyODQ4NDUxLCJleHAiOjE3MTI4NTIwNTF9.XQvF8M9nCOlBh02jf5RbjLaLh44K4nY1gHbF4aZMVpk


### creating tasks
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjczLCJlbWFpbCI6InB1amFAZ21haWwuY29tIiwiaWF0IjoxNzEyODQ4NDUxLCJleHAiOjE3MTI4NTIwNTF9.XQvF8M9nCOlBh02jf5RbjLaLh44K4nY1gHbF4aZMVpk

{
    "title": "readme banana",
    "description": "pandoc"
}

###update
PUT http://localhost:3000/tasks/41
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjczLCJlbWFpbCI6InB1amFAZ21haWwuY29tIiwiaWF0IjoxNzEyODQ4NDUxLCJleHAiOjE3MTI4NTIwNTF9.XQvF8M9nCOlBh02jf5RbjLaLh44K4nY1gHbF4aZMVpk

{
  "title": "testing",
  "description": "ho gaya"
}

### delete
DELETE http://localhost:3000/tasks/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjczLCJlbWFpbCI6InB1amFAZ21haWwuY29tIiwiaWF0IjoxNzEyODQ4NDUxLCJleHAiOjE3MTI4NTIwNTF9.XQvF8M9nCOlBh02jf5RbjLaLh44K4nY1gHbF4aZMVpk

### delete user and data
DELETE http://localhost:3000/deluser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjczLCJlbWFpbCI6InB1amFAZ21haWwuY29tIiwiaWF0IjoxNzEyODQ4NDUxLCJleHAiOjE3MTI4NTIwNTF9.XQvF8M9nCOlBh02jf5RbjLaLh44K4nY1gHbF4aZMVpk


